export const C = {
  bg: "var(--bg)",
  card: "var(--card)",
  border: "var(--border)",
  textPrimary: "var(--text-primary)",
  textMuted: "var(--text-muted)",
  green: "var(--color-green)",
  teal: "var(--color-teal)",
  gray: "var(--color-gray)",
  pink: "var(--color-pink)",
  blueLight: "var(--color-blue-light)",
  blueDark: "var(--color-blue-dark)",
  orange: "var(--color-orange)",
  red: "var(--color-red)",
  purple: "var(--color-purple)",
};
